language: csharp
solution: EfEnumToLookup.sln
install:
  - nuget restore EfEnumToLookup.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release EfEnumToLookup.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./EfEnumToLookupTests/bin/Release/EfEnumToLookup.dll
